apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: web
spec:
  containers:
  - name: web
    image: vaymon/nginx:v2
    volumeMounts:
      - name: app
        mountPath: /app

  initContainers:
    - name: initweb
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app

  volumes:
    - name: app
      emptyDir: {}
